/*
 * Generated by the Mule project wizard. http://mule.mulesoft.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.module.mappack.config;

import org.mule.module.mappack.elements.DateTimeMapValue;
import org.mule.module.mappack.elements.Maporder;
import org.mule.module.mappack.elements.Mapvalue;
import org.mule.module.mappack.elements.TransformMapValue;
import org.springframework.beans.factory.xml.NamespaceHandlerSupport;


public class MapPackNamespaceHandler extends NamespaceHandlerSupport
{
    public void init()
    {
        registerBeanDefinitionParser("nested-map-transformer", new NestedMapDefinitionParser());
        registerBeanDefinitionParser("mapvalue", new MapValueDefinitionParser("mapvalue", Mapvalue.class));
        registerBeanDefinitionParser("date-time-mapvalue", new DateTimeMapValueDefinitionParser(DateTimeMapValue.class));
        registerBeanDefinitionParser("transform-mapvalue", new TransformMapValueDefinitionParser("mapvalue", TransformMapValue.class));
        registerBeanDefinitionParser("maporder", new MapValueDefinitionParser("maporder", Maporder.class));
    }
}
