/*
 * Generated by the Mule project wizard. http://mule.mulesoft.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.module.nestedmappack;

import org.mule.tck.FunctionalTestCase;

public class MapPackNamespaceHandlerTestCase extends FunctionalTestCase
{
    protected String getConfigResources()
    {
        return "mappack-namespace-config.xml";
    }

    public void testFilepackConfig() throws Exception
    {

        return;
    }
}
